name: PHPUnit test & Static code analysis

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - LICENSE

env:
  XDEBUG_MODE: coverage

permissions:
  contents: read

jobs:
  build:
    name: symfony-baseapp-bundle (PHP ${{ matrix.php-versions }})

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2']

    steps:
    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ctype, iconv
        coverage: xdebug
        tools: composer

    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-versions }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --optimize-autoloader

    - name: Run all test suites
      run: vendor/bin/phpunit --testsuite=all --coverage-text
       
    - name: Psalm static code analysis
      run: vendor/bin/psalm
